rule all:
    input:
        "resources/data_premh.jld2",
        "resources/data_postmh.jld2",
        "resources/sens_wd_data_premh.jld2",
        "resources/sens_wd_data_postmh.jld2",
        "resources/sens_we_data_premh.jld2",
        "resources/sens_we_data_postmh.jld2",
        "resources/sens_missingness_data_premh.jld2",
        "resources/sens_missingness_data_postmh.jld2",
        "resources/sens_conf_data_premh.jld2",
        "resources/sens_conf_data_postmh.jld2",
        "resources/imputed_data_premh.jld2",
        "resources/imputed_data_postmh.jld2",
        "resources/R_imputed_data_premh.jld2",
        "resources/R_imputed_data_postmh.jld2",
        "resources/imputed_data_sens_auxil_premh.jld2",
        "resources/imputed_data_sens_auxil_postmh.jld2",
        "resources/imputed_data_sens_wd_premh.jld2",
        "resources/imputed_data_sens_wd_postmh.jld2",
        "resources/imputed_data_sens_we_premh.jld2",
        "resources/imputed_data_sens_we_postmh.jld2",
        "resources/imputed_data_sens_missingness_premh.jld2",
        "resources/imputed_data_sens_missingness_postmh.jld2",
        "resources/imputed_data_sens_conf_premh.jld2",
        "resources/imputed_data_sens_conf_postmh.jld2"

rule data_prep:
    input:
        "resources/tm_bout_statistics.csv",
        "resources/tm_sens_wd_bout_statistics.csv",
        "resources/tm_sens_we_bout_statistics.csv",
        "resources/tm_bout_statistics_confunbounded.csv",
        "resources/PII_Clean_Teen_Surveys_2023-03-21.csv",
        "resources/PII_Clean_Parent_Surveys_2023-03-21.csv",
        "resources/tm_missings_summary.csv"
    output:
        "resources/data_premh.jld2",
        "resources/data_postmh.jld2",
        "resources/sens_wd_data_premh.jld2",
        "resources/sens_wd_data_postmh.jld2",
        "resources/sens_we_data_premh.jld2",
        "resources/sens_we_data_postmh.jld2",
        "resources/sens_missingness_data_premh.jld2",
        "resources/sens_missingness_data_postmh.jld2",
        "resources/sens_conf_data_premh.jld2",
        "resources/sens_conf_data_postmh.jld2"
    script:
        "scripts/data_prep.jl"

rule multiple_imputation:
    threads: 2
    input:
        "resources/data_premh.jld2",
        "resources/data_postmh.jld2"
    output:
        "resources/imputed_data_premh.jld2",
        "resources/imputed_data_postmh.jld2",
    script:
        "scripts/multiple_imputation.jl"

rule R_multiple_imputation:
    threads: 2
    input:
        "resources/data_premh.jld2",
        "resources/data_postmh.jld2"
    output:
        "resources/R_imputed_data_premh.jld2",
        "resources/R_imputed_data_postmh.jld2"
    script:
        "scripts/R_multiple_imputation.jl"

rule sens_multiple_imputation:
    threads: 10
    input:
        "resources/data_premh.jld2",
        "resources/data_postmh.jld2",
        "resources/sens_wd_data_premh.jld2",
        "resources/sens_wd_data_postmh.jld2",
        "resources/sens_we_data_premh.jld2",
        "resources/sens_we_data_postmh.jld2",
        "resources/sens_missingness_data_premh.jld2",
        "resources/sens_missingness_data_postmh.jld2",
        "resources/sens_conf_data_premh.jld2",
        "resources/sens_conf_data_postmh.jld2"
    output:
        "resources/imputed_data_sens_auxil_premh.jld2",
        "resources/imputed_data_sens_auxil_postmh.jld2",
        "resources/imputed_data_sens_wd_premh.jld2",
        "resources/imputed_data_sens_wd_postmh.jld2",
        "resources/imputed_data_sens_we_premh.jld2",
        "resources/imputed_data_sens_we_postmh.jld2",
        "resources/imputed_data_sens_missingness_premh.jld2",
        "resources/imputed_data_sens_missingness_postmh.jld2",
        "resources/imputed_data_sens_conf_premh.jld2",
        "resources/imputed_data_sens_conf_postmh.jld2"
    script:
        "scripts/sens_multiple_imputation.jl"